### PR TITLE
Appveyor CI (2)

### PR DESCRIPTION
**Pull request by campagnola**
Work in progress..

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Tell me when I can merge.

**Comment by campagnola** [comment]
Still fighting it. I have tests passing in my VM, but I'm still getting weird errors on appveyor.

**Comment by samuelgarcia** [comment]
I am about to merge PR#55.

Is this PR still valid ?

Where is the appveyor for pyacq ?

**Comment by campagnola** [comment]
I never managed to get tests passing on appveyor (even when they passed on other windows machines). I can try it again after this round of bug fixes..

**Comment by samuelgarcia** [comment]
OK.
I think it could be could having tests on appveyor settled even if they do not pass.
What do you think ?

**Comment by campagnola** [comment]
I think this is safe to merge (and plus having it merged should make it easier to deal with appveyor).

**Comment by samuelgarcia** [comment]
OK.

**Comment by samuelgarcia** [comment]
Oups. I can't merge this merge because this is not synchro with the master....

**Comment by campagnola** [comment]
Ready!

**Comment by samuelgarcia** [comment]
Oh yeah.

**Pull request merged**
