### PR TITLE
Some stuff needed for onlinespikesorting project : filter

### PR DESCRIPTION
**Pull request by samuelgarcia**
This depend on PR#38
This mainly introduce Second Order Filter nodes.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi luke.
I have again problem with seg fault in this PR.
Could you tell me again what your dignostic about sockets in timefreqs ?

**Comment by campagnola** [comment]
#42 is the only segfault source I have been able to identify so far.

**Comment by campagnola** [comment]
Any idea about the one failing test?
https://travis-ci.org/pyacq/pyacq/builds/97444332#L582

**Comment by samuelgarcia** [comment]
This is not passing tests but need to be incorparated in master.
A new branch will created for debugiing everything at once.

**Pull request merged**
