### PR TITLE
Testing for travis errors

### PR DESCRIPTION
**Pull request by campagnola**
(do not merge)

### CODE REVIEW

**Comment by samuelgarcia** [comment]
When need to handle QSignal in a Node is it possible to have QSignal with object.
I propose:
BaseNode(object)
Node(BaseNode, QObjetc)
NodeWidget(BaseNode, QWidget)

**Comment by campagnola** [comment]
Are there any nodes that emit signals? 

In the past I have handled it like this:

```
class MyClass(object):
    # Only used for emitting signals:
    class SignalProxyObject(QtCore.QObject):
        my_signal = QtCore.Signal()
    
    def __init__(self):
        self.__sig_proxy = MyClass.SignalProxyObject()
        self.my_signal = self.__sigProxy.my_signal
```

**Comment by samuelgarcia** [comment]
Yes there are some nodes in all PR I made. I will have a look.
I finally propose:
Node(object)
QNode(Node, QObject)
QWidgetNode(Node, QWidget)

So each can inherits what it needs.

**Comment by campagnola** [comment]
If the only purpose of QNode is to introduce QObject as a superclass, then why not just do that for the subclasses that require it? 

Instead of this:

```
Node(object)
QNode(Node, QObject)
MyQNode(QNode)
```

Why not this:

```
Node(object)
MyQNode(Node, QObject)
```

**Comment by samuelgarcia** [comment]
I would like at least QWidgetNode because close is more tricky (2 meaning :  QWidget.close and Node.close).

**Comment by campagnola** [comment]
Agreed.

**Comment by samuelgarcia** [comment]
OK so I mergel this patch in my samuel.garcia:device-pyaudio
And pull it in all my branches to see what append.
OK ?

**Comment by campagnola** [comment]
+1

**Pull request closed without merging**
