### PR TITLE
Nidaqmx

### PR DESCRIPTION
**Pull request by samuelgarcia**
New Nidaqmx Node based on the official python wrapepr from ni.

### CODE REVIEW

**Comment by campagnola** [comment]
Looks like there is some code to support analog output channels.. is this just not finished yet?

**Comment by samuelgarcia** [comment]
For the first round it is finished. Until the enxt bug.

The scenario is: coninuous acquisition on input. And episodic play some signal on output (at the same sample rate). So that feed my needs for the moments.

We should also add digital input/output but this will be for next time.

**Comment by campagnola** [comment]
Error running the example:

```
Traceback (most recent call last):
  File "c:\users\lukec\pyacq\pyacq\devices\ni_daqmx.py", line 232, in run
    nb_sample = aitask.in_stream.readinto(raw_data_flat)
  File "C:\Anaconda3\lib\site-packages\nidaqmx\_task_modules\in_stream.py", line 1992, in readinto
    self.timeout)
  File "C:\Anaconda3\lib\site-packages\nidaqmx\_task_modules\read_functions.py", line 583, in _read_raw
    ctypes.byref(number_of_bytes_per_sample), None)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by samuelgarcia** [comment]
You need this: https://github.com/ni/nidaqmx-python/pull/45

**Comment by campagnola** [comment]
Thanks! Works well on my end with a USB-6259.

**Comment by samuelgarcia** [comment]
I will merge this.

**Pull request merged**
