### PR TITLE
update appveyor config

### PR DESCRIPTION
**Pull request by campagnola**

### CODE REVIEW

**Comment by campagnola** [comment]
I copied some appveyor configuration changes from vispy, almost working.
Only a couple of failures.. @samuelgarcia have you seen these before?

**Comment by Lx37** [comment]
#91 needs to be integrated to success the checking

**Comment by samuelgarcia** [comment]
I guess we should also change the travis configuration to also test with python3.6.

**Comment by samuelgarcia** [comment]
I merge now.
I will fix the TriggerAccumalator error later.

**Pull request merged**
