### PR TITLE
National Instruments DAQmx

### PR DESCRIPTION
**Pull request by campagnola**
WIP: beginning of DAQmx support.

### CODE REVIEW

**Comment by campagnola** [comment]
Status: multichannel analog input works; need to add analog output and digital I/O.

**Comment by samuelgarcia** [comment]
NI have released an official open source python wrapper for there dll.
It is here https://github.com/ni/nidaqmx-python

I plan to write a new Node based on you one and but using the official DDL, I guess it is better for the long term.

**Comment by samuelgarcia** [comment]
I propose to close this PR and use #72 instead.

@campagnola : if you have time to have a look at #72...

**Comment by samuelgarcia** [comment]
Close this because implemented in #72.

**Pull request closed without merging**
