### PR TITLE
SImple node recorder: RawRecorder.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by campagnola** [comment]
Looks good to me, although it would be really nice to have a class (or functions) that formalize this new data format. It'd be ok to have that in a separate PR, though.

**Comment by samuelgarcia** [comment]
Formating data need some clarification at stream level with gain/offset/dtype be able to store in raw format (int16) or in scaled format (float32/64) with units.

What is the choice for that in acq4 ?

For next time, I think.

**Comment by campagnola** [comment]
ACQ4 stores data as HDF5 so shape/dtype are not issues, and all scale/offset are applied immediately after acquiring the data. It would be nice here just to have a function that can correctly recreate a memmapped array from the stored structure.

**Comment by samuelgarcia** [comment]
Iw ill merge.

**Pull request merged**
